// Clé TSIG pour les mises à jour dynamiques
// En production : générée avec dnssec-keygen ou tsig-keygen
// Ici : clé faible volontairement pour le hackathon
key "exfil-key" {
    algorithm hmac-sha256;
    secret "R2hvc3RQaXBlSGFja2F0aG9uMjAyNiFFeGZpbA==";
};
